### ISSUE TITLE
Start of compress middleware

### ISSUE THREAD

**Issue by gsquire** [iron/compress#1]
I have started the implementation of this middleware. The encoders cannot be shared across threads however since the Send trait is not implemented for them.

https://github.com/gsquire/compress

**Comment by alilleybrinker** [comment]
Any word on what the plan is for this? I could use a good compression middleware.

**Comment by gsquire** [comment]
@reem I know this is a rough start, but are you still considering including this in Iron? I couldn't make a PR as it is an empty repository.

**Comment by reem** [comment]
@gsquire I am still looking to include this in iron, sorry for not getting back to you earlier. Unfortunately, I think the design will need to change a bit since the body abstraction in iron changed from `Box<Read>` to `Box<WriteBody>` where WriteBody is a custom trait in iron that has one method which takes a writer vs. being a reader. This allows for more natural implementations but is inconvenient in cases like this.

**Comment by gsquire** [comment]
@reem I guess the code went stale after a while. I can read the docs on that then and see if I can't update it a bit. Thanks for responding.

**Comment by gsquire** [comment]
@reem [This](https://github.com/gsquire/compress/commit/87ce1808796ce2dfc357b5a5e55d9b1bc543987c) commit is almost there (so I think). I don't know if it's the correct approach, I just need to find a way to read the original body to compress it.

**Comment by gsquire** [comment]
@reem At this point, I don't know what the best approach will be for this. Since I need to incorporate the compression engine somehow, I don't know what the best entry point will be for that in the request to response flow. Once the response is compressed however, it returns a slice of bytes which can take advantage of the `WriteBody` trait implemented for it. What are your thoughts on ensuring that the response can use the `EncoderWriter` in the flate2 crate?

**Comment by gsquire** [comment]
@AndrewBrinker @reem After reading through the Iron docs, I figured why not use a modifier instead of middleware? And I was finally able to write something that can compress bytes. Here is the commit that changed it: https://github.com/gsquire/compress/commit/2982894f8580155f6a70f121269842ab697019db

Let me know if it looks good, needs work, etc.
